max_speed_kbps : 1000
start_time : '00:00'
intervals:
  - duration_minutes : 60
    speed_percentage : 0
 
  - duration_minutes : 60
    speed_percentage : 25
 
  - duration_minutes : 60
    speed_percentage : 50 
 
  - duration_minutes : 60
    speed_percentage : 75

  - duration_minutes : 60
    speed_percentage : 100
 
  - duration_minutes : 60
    speed_percentage : 0