max_speed_kbps: 24000
network_interface: 'wlp1s0'
start_time: '23:07'
intervals:
  - duration_minutes: 1
    speed_percentage: 0

  - duration_minutes: 1
    speed_percentage: 25

  - duration_minutes: 1
    speed_percentage: 50

  - duration_minutes: 1
    speed_percentage: 75
    
  - duration_minutes: 1
    speed_percentage: 100

  - duration_minutes: 1
    speed_percentage: 0
