max_speed: 1000
start_time: 02:04
intervals:
  - duration: 1
    speed_percentage: 100
  - duration: 1
    speed_percentage: 75
  - duration: 1
    speed_percentage: 50
  - duration: 1
    speed_percentage: 25
  - duration: 1
    speed_percentage: 0
